name: Practica6
description: Una nueva aplicación para convertir.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6  # O usa la versión más reciente disponible

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
